# gitlab-ci

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"

cache:
  paths:
    - ./.m2/repository

stages:
  - build
  - releases
  - deploy

before_script:
  - curl -s toast.sh/install-v3 | bash

build:
  stage: build
  image: maven:latest
  script:
    - ~/toaster/toast.sh build version
    - mvn package
  artifacts:
    paths:
      - target/

releases:
  stage: releases
  image: python:latest
  script:
    - pip install awscli
    - ~/toaster/toast.sh prepare
    - ~/toaster/toast.sh releases beanstalk LatestVersion
  artifacts:
    paths:
      - target/

deploy-dev:
  stage: deploy
  image: python:latest
  when: manual
  only:
    - master
  script:
    - pip install awscli
    - ~/toaster/toast.sh deploy beanstalk nalbam-bot-dev LatestVersion

deploy-prod:
  stage: deploy
  image: python:latest
  when: manual
  only:
    - master
  script:
    - pip install awscli
    - ~/toaster/toast.sh deploy beanstalk nalbam-bot-prod LatestVersion

after_script:
  - ls -alh target
