# gitlab-ci

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"

cache:
  paths:
    - ./.m2/repository

stages:
  - test
  - build
  - release
  - deploy

before_script:
  - curl -s toast.sh/install-v3 | bash

test:
  stage: test
  image: maven:latest
  script:
    - mvn test

build:
  stage: build
  image: maven:latest
  script:
    - ~/toaster/toast.sh build version
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/

release:
  stage: release
  image: python:latest
  script:
    - pip install awscli
    - ~/toaster/toast.sh prepare
    - ~/toaster/toast.sh release beanstalk
  artifacts:
    paths:
      - target/

deploy-dev:
  stage: deploy
  image: python:latest
  only:
    - dev
  script:
    - pip install awscli
    - ~/toaster/toast.sh deploy beanstalk nalbam-bot-dev

deploy-qa:
  stage: deploy
  image: python:latest
  only:
    - master
  script:
    - pip install awscli
    - ~/toaster/toast.sh deploy beanstalk nalbam-bot-qa

deploy-prod:
  stage: deploy
  image: python:latest
  when: manual
  only:
    - master
  script:
    - pip install awscli
    - ~/toaster/toast.sh deploy beanstalk nalbam-bot-prod

after_script:
  - ls -alh target
