server:
  port: 8080

spring:
  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  redis:
    host: localhost
    database: 5

logging:
  level:
    com.nalbam: DEBUG

nalbam:
  app:
    name: bot
    base: com.nalbam
  trade:
    buy:
      per: 0.03
      krw: 30000
    sell:
      per: 0.03
      btc: 0.01
  aws:
    api: ${AWS_API_URL:https://au43186kfk.execute-api.ap-northeast-2.amazonaws.com/prod/token}
    key: ${AWS_API_KEY:AWS_API_KEY}
  korbit:
    api: ${KORBIT_API_URL:https://api.korbit.co.kr/v1}
    client_id: ${KORBIT_ACCESS_KEY:KORBIT_ACCESS_KEY}
    client_secret: ${KORBIT_SECRET_KEY:KORBIT_SECRET_KEY}
    grant_type: ${KORBIT_GRANT_TYPE:password}
    username: ${KORBIT_USERNAME:username}
    password: ${KORBIT_PASSWORD:password}
