server:
  port: 8080

spring:
  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  redis:
    host: localhost
    database: 5

logging:
  level:
    com.nalbam: DEBUG

nalbam:
  app:
    name: bot
    base: com.nalbam
  cache:
    expire: 600
  trade:
    buy:
      per: 0.03
      krw: 5000
    sell:
      per: 0.03
      krw: 5000
    init:
      krw: 100000
  coinone:
    access-key: ${COINONE_ACCESS_KEY}
    secret-key: ${COINONE_SECRET_KEY}
  korbit:
    access-key: ${KORBIT_ACCESS_KEY}
    secret-key: ${KORBIT_SECRET_KEY}
