server:
  port: 8080

spring:
  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  package: com.nalbam
  product: nalbam-bot
  profile: ${PROFILE:default}

aws:
  region: ${AWS_REGION:ap-northeast-2}
  bucket: ${AWS_BUCKET:repo-me17-seoul}
  key:
    access: ${AWS_ACCESS_KEY:STRING}
    secret: ${AWS_SECRET_KEY:STRING}
  api:
    url: ${AWS_API_URL:https://au43186kfk.execute-api.ap-northeast-2.amazonaws.com/prod}
    key: ${AWS_API_KEY:STRING}
  sqs:
    queueName: bot
    maxTimeout: ${AWS_SQS_MAX_TIMEOUT:36000}
    maxDelay: ${AWS_SQS_MAX_DELAY:900}
    endPoint: sqs.${AWS_REGION:ap-northeast-2}.amazonaws.com

coinone:
  api: ${COINONE_API_URL:https://api.coinone.co.kr/v2}
  access_token: ${COINONE_ACCESS_TOKEN:STRING}
  secret_key: ${COINONE_SECRET_KEY:STRING}
  enabled: false

korbit:
  api: ${KORBIT_API_URL:https://api.korbit.co.kr/v1}
  client_id: ${KORBIT_ACCESS_KEY:STRING}
  client_secret: ${KORBIT_SECRET_KEY:STRING}
  username: ${KORBIT_USERNAME:username}
  password: ${KORBIT_PASSWORD:password}
  enabled: false

trade:
  sell:
    per: 0.005
    amt: 0.01
    min: 0.001
    sgn: 3
  buy:
    per: 0.005
    amt: 50000
    min: 5000
    sgn: 3

slack:
  webhook: ${SLACK_WEBHOOK:https://hooks.slack.com/services/web/hook/token}
  channel: ${SLACK_CHANNEL:sandbox}

logzio:
  token: ${LOGZIO_TOKEN:STRING}

logging:
  level:
    com.nalbam: DEBUG
