server:
  port: 8080

spring:
  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    com.nalbam: DEBUG

nalbam:
  app:
    name: bot
    base: com.nalbam
  trade:
    sell:
      per: 0.003
      amt: 0.01
      min: 0.01
      sgn: 3
    buy:
      per: 0.003
      amt: 50000
      min: 500
      sgn: 3
  aws:
    api: ${AWS_API_URL:https://au43186kfk.execute-api.ap-northeast-2.amazonaws.com/prod}
    key: ${AWS_API_KEY:AWS_API_KEY}
  korbit:
    api: ${KORBIT_API_URL:https://api.korbit.co.kr/v1}
    client_id: ${KORBIT_ACCESS_KEY:KORBIT_ACCESS_KEY}
    client_secret: ${KORBIT_SECRET_KEY:KORBIT_SECRET_KEY}
    username: ${KORBIT_USERNAME:username}
    password: ${KORBIT_PASSWORD:password}
  slack:
    webhook: ${SLACK_WEBHOOK:https://hooks.slack.com/services/a/b/c}
    channel: ${SLACK_CHANNEL:sandbox}
