#
# CircleCI 2.0
#
version: 2
jobs:
  build:
    docker:
      - image: nalbam/builder:maven
    steps:
      - checkout
      - run: mvn test

workflows:
  version: 2
  lambda:
    jobs:
      - build
